chore: bump node version (#30)
Co-authored-by: Vasil Angelov <vasilangelov@VASIL-MAC.local>

diff --git a/.github/workflows/validate-pull-request-changes.yml b/.github/workflows/validate-pull-request-changes.yml
--- a/.github/workflows/validate-pull-request-changes.yml
+++ b/.github/workflows/validate-pull-request-changes.yml
@@ -6,9 +6,6 @@ on:
   pull_request:
     branches: [main]
 
-env:
-  NODE_JS_VERSION: "22.21.1"
-
 permissions:
   contents: read
 
@@ -22,10 +19,21 @@ jobs:
         uses: actions/checkout@v5
         with:
           ref: ${{ github.event.pull_request.head.sha }}
+      - name: Read node version
+        id: get_node_version
+        run: |
+          node_version=$(jq -re '.engines.node' ./package.json)
+
+          if [[ ! "$node_version" =~ ^([0-9]{1,2}\.){0,2}[0-9]{1,2}$ ]]; then
+            echo "::error title=Invalid node version::Got: $node_version (expected x.y.z, x.y or x)"
+            exit 1
+          fi
+
+          echo "node_version=$node_version" >> "$GITHUB_OUTPUT"
       - name: Setup node
         uses: actions/setup-node@v5
         with:
-          node-version: ${{ env.NODE_JS_VERSION }}
+          node-version: ${{ steps.get_node_version.outputs.node_version }}
           cache: npm
           package-manager-cache: true
           cache-dependency-path: package-lock.json
